POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYwMTdiZTAyMjYwYzE4MjAwMTgwOThkOCIsImlhdCI6MTYxMjE2OTM4Mn0.pvy4XmSAhZGkI3X71Ce6fM9Dc-adeKg6cj33TL-gK7Q

{ 
    "title": "uusitesti", 
    "url": "jeejee.com", 
    "userId": "6017be02260c1820018098d8"
}


###

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJldHVwZWtrYSIsImlkIjoiNjAxN2JlOGUyNjBjMTgyMDAxODA5OGRhIiwiaWF0IjoxNjEyMTY4ODY2fQ.hScDr6oIKKRnXNLYHMrhiSRT8JQKkrrwxXXVmP64fhE

{ 
    "title": "BLOG TEST FOR COMMENT", 
    "url": "jeejee.com", 
    "userId": "5c7f8eb616ec9861d530d938"
}


### 

DELETE http://localhost:3001/api/blogs/602a4ecf7c3d9b4b4594868a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJldHVwZWtrYSIsImlkIjoiNjAxN2JlOGUyNjBjMTgyMDAxODA5OGRhIiwiaWF0IjoxNjEyMTY4ODY2fQ.hScDr6oIKKRnXNLYHMrhiSRT8JQKkrrwxXXVmP64fhE

###

PUT http://localhost:3001/api/blogs/6017bb8c1130d21becbc5a3b
Content-Type: application/json

{
    "title": "thisisamodifiedblog",
    "likes": 100
}

###
POST http://localhost:3001/api/blogs/602a4f0b4bfa5b4c23820f66/comments
Content-type: application/json

{
    "comment": "This is a new comment for testing"
}